# Generated by Django 5.0.6 on 2025-12-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
