# Generated by Django 5.0.6 on 2025-12-08 21:39

from django.db import migrations, models


def asignar_dueño_al_primer_usuario(apps, schema_editor):
    """
    Asigna el rol de dueño al primer usuario creado (menor id_usuario).
    """
    Usuario = apps.get_model('usuario', 'Usuario')
    
    # Obtener el primer usuario (menor id_usuario) que no esté eliminado
    primer_usuario = Usuario.objects.filter(eliminado=False).order_by('id_usuario').first()
    
    if primer_usuario:
        # Asignar dueño al primer usuario si no lo tiene ya
        if not primer_usuario.es_dueño:
            primer_usuario.es_dueño = True
            primer_usuario.save(update_fields=['es_dueño'])


def revertir_asignacion(apps, schema_editor):
    """
    Función de reversión (opcional).
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_dueño',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(asignar_dueño_al_primer_usuario, revertir_asignacion),
    ]
