"""
Django settings for proyecto_principal project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
import dj_database_url

# Configurar PyMySQL como driver de MySQL (necesario para Vercel/serverless)
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-00(4a2#*856p*&k(fa8aj+mv6c0tvs$)jo*u(w9)bdqx#!th!8')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'usuario',
    'home',
    'categoria',
    'proveedor',
    'producto',
    'venta',
    'estadistica',
    'compra',
    'sucursal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'proyecto_principal.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'proyecto_principal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'proyecto_principal.context_processors.usuario_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_principal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Prioridad 1: Si existe DATABASE_URL (para bases de datos en línea como Render, Railway, etc.)
DATABASE_URL = os.environ.get('DATABASE_URL') or config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Configuración para base de datos en línea (PostgreSQL, MySQL, etc.)
    # Asegurar que la URL tenga parámetros SSL si es PostgreSQL
    if DATABASE_URL.startswith('postgresql://'):
        # Remover parámetros SSL existentes para reconfigurarlos
        if '?' in DATABASE_URL:
            base_url, params = DATABASE_URL.split('?', 1)
            # Remover sslmode si existe
            params_list = [p for p in params.split('&') if not p.startswith('sslmode=')]
            DATABASE_URL = base_url + ('?' + '&'.join(params_list) if params_list else '')
        # Agregar sslmode=prefer (más tolerante que require)
        separator = '?' if '?' not in DATABASE_URL else '&'
        DATABASE_URL = f"{DATABASE_URL}{separator}sslmode=prefer"
    
    # Configurar base de datos con opciones SSL explícitas para PostgreSQL
    db_config = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
    
    # Agregar opciones SSL adicionales para PostgreSQL si es necesario
    if db_config.get('ENGINE') == 'django.db.backends.postgresql':
        # Configuración SSL más robusta para Render
        # prefer intenta SSL pero es más tolerante con errores de conexión
        db_config['OPTIONS'] = {
            'sslmode': 'prefer',  # Más tolerante que 'require'
            'connect_timeout': 15,
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        }
        # Configuración adicional para conexiones persistentes
        db_config['CONN_MAX_AGE'] = 300  # Reducir tiempo de conexión persistente
    elif db_config.get('ENGINE') == 'django.db.backends.mysql':
        # Configuración para MySQL con PyMySQL (compatible con Vercel/serverless)
        db_config['OPTIONS'] = {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
        # Reducir tiempo de conexión persistente para entornos serverless
        db_config['CONN_MAX_AGE'] = 0  # Desactivar conexiones persistentes en serverless
    
    DATABASES = {
        'default': db_config
    }
else:
    # Configuración para base de datos local (fallback)
    # Usa variables de entorno o configura en .env
    db_engine = config('DB_ENGINE', default='django.db.backends.sqlite3')
    db_config = {
        'ENGINE': db_engine,
        'NAME': config('DB_NAME', default=BASE_DIR / 'db.sqlite3'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
    }
    
    # Si es MySQL, agregar opciones para PyMySQL
    if db_engine == 'django.db.backends.mysql':
        db_config['OPTIONS'] = {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    
    DATABASES = {
        'default': db_config
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT debe estar en la raíz del proyecto para que Vercel pueda acceder
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Carpeta static en la raíz del proyecto
]

# Finders para buscar archivos estáticos en las apps
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# WhiteNoise para servir archivos estáticos en producción
# En Vercel/serverless, usar CompressedStaticFilesStorage (sin manifest)
# Esto permite que WhiteNoise busque archivos en tiempo de ejecución si no están en staticfiles
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Configuración de WhiteNoise optimizada para Vercel/serverless
# WHITENOISE_USE_FINDERS permite buscar archivos en STATICFILES_DIRS y apps si no están en staticfiles
# Esto es importante en Vercel porque los archivos pueden no estar en la ubicación esperada
WHITENOISE_USE_FINDERS = True  # CRÍTICO: Permite buscar archivos en tiempo de ejecución
WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh solo en desarrollo
# Crear el directorio STATIC_ROOT si no existe (solo en desarrollo local, no en Vercel)
# En Vercel el sistema de archivos es de solo lectura, así que solo intentamos en desarrollo
# y manejamos el error silenciosamente si no se puede crear
import os
if DEBUG:
    try:
        if not os.path.exists(STATIC_ROOT):
            os.makedirs(STATIC_ROOT, exist_ok=True)
    except (OSError, PermissionError):
        # Ignorar errores si no se puede crear (ej: sistema de solo lectura en Vercel/serverless)
        pass
WHITENOISE_ROOT = STATIC_ROOT  # Directorio donde están los archivos recopilados
WHITENOISE_MANIFEST_STRICT = False  # No fallar si falta un archivo
WHITENOISE_MAX_AGE = 31536000  # Cache por 1 año
WHITENOISE_INDEX_FILE = False  # No buscar index.html

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de login
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/inicio/'
LOGOUT_REDIRECT_URL = '/'
'''
# Correo de prueba con consola
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@tuapp.com'
'''
#Envio de correos con Gmail-> Verificacion de dos pasos y contraseña de aplicación
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'migoutlet.verificacion@gmail.com'#Mail de prueba
EMAIL_HOST_PASSWORD = 'bppe anpo ufeq tckt'  # la que creaste, no tu contraseña normal-> GOOGLE DJANGO
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
